apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-qvib
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-qvib
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-qvib
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-qvib
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-qvib
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-ncej-tenant/rhtap-demo-app/hacbs-test-project-qvib@sha256:d504cbe5505d5e7ffd986ab01d06feacfc94234e6eda1e961350cfb441475d87
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
