apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-qvib
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-ncej-tenant/rhtap-demo-app/hacbs-test-project-qvib@sha256:b50131ed40e38cf7de6a5c6cb4628b8616cc345c7efd7069daaef5fa42c03ef5
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
